"""init

Revision ID: 22a36a2accd6
Revises: 
Create Date: 2020-08-18 16:54:08.431778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a36a2accd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('area', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('enname', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('curr_type', sa.String(length=64), nullable=True),
    sa.Column('list_status', sa.String(length=64), nullable=True),
    sa.Column('list_date', sa.String(length=64), nullable=True),
    sa.Column('delist_date', sa.String(length=64), nullable=True),
    sa.Column('is_hs', sa.String(length=8), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
