"""circ

Revision ID: 4ecdcb037ed2
Revises: efb8ef98d6ee
Create Date: 2020-09-04 09:33:22.147565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecdcb037ed2'
down_revision = 'efb8ef98d6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupstocks',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], )
    )
    op.add_column('stocks', sa.Column('circ_mv', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'circ_mv')
    op.drop_table('groupstocks')
    # ### end Alembic commands ###
