"""day

Revision ID: 653fb6b37932
Revises: 22a36a2accd6
Create Date: 2020-08-20 10:05:47.364575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653fb6b37932'
down_revision = '22a36a2accd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('turnover_rate_f', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('ps', sa.Float(), nullable=True),
    sa.Column('ps_ttm', sa.Float(), nullable=True),
    sa.Column('dv_ratio', sa.Float(), nullable=True),
    sa.Column('dv_ttm', sa.Float(), nullable=True),
    sa.Column('total_share', sa.Float(), nullable=True),
    sa.Column('float_share', sa.Float(), nullable=True),
    sa.Column('free_share', sa.Float(), nullable=True),
    sa.Column('total_mv', sa.Float(), nullable=True),
    sa.Column('circ_mv', sa.Float(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days')
    # ### end Alembic commands ###
