"""circ2

Revision ID: cf0a97f923db
Revises: 4ecdcb037ed2
Create Date: 2020-09-04 15:28:13.376583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0a97f923db'
down_revision = '4ecdcb037ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('pe', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'pe')
    # ### end Alembic commands ###
