/* 用户 */
CREATE TABLE IF NOT EXISTS `users`  (
	`id` INT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
	`uid` VARCHAR(256) COMMENT 'UID',
	`permission` JSON COMMENT '权限',
	`updatedat` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`createdat` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	PRIMARY KEY (`id`),
	UNIQUE INDEX (`uid`)
) CHARACTER SET = utf8mb4;
