/* 资源 */
CREATE TABLE IF NOT EXISTS `resources`  (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(256) COMMENT '名称',
    `description` TEXT COMMENT '描述',
    `action` JSON COMMENT '对应的权限',
    `updatedat` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `createdat` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE INDEX (`name`)
) CHARACTER SET = utf8mb4;
